import type { Result } from '../types/result';
import { err, ok } from '../types/result';
import { semanticSearchService } from './SemanticSearchService';
import { readLocalCandidates } from './LocalCandidateStore';
export interface SearchToolParams { query: string; limit?: number; filters?: Record<string, unknown> }
export interface SearchToolResult<T> { results: T[]; metadata?: Record<string, unknown>; toolName: string }
export interface SearchTool<TParams, TResult> { name: string; description: string; execute(params: TParams): Promise<Result<SearchToolResult<TResult>>> }
type CandidateSearchRecord = Record<string, unknown> & { id: string; name: string; role?: string; title?: string; similarity?: number; skills?: string[]; contentSnippet?: string };
export class KeywordSearchTool implements SearchTool<SearchToolParams, CandidateSearchRecord> { name = 'keyword_search'; description = 'Search local candidate profiles for exact keywords.'; async execute({ query, limit = 10 }: SearchToolParams): Promise<Result<SearchToolResult<CandidateSearchRecord>>> { const needle = query.toLowerCase(); const results = readLocalCandidates().filter((candidate) => [candidate.name, candidate.role, candidate.title, candidate.location, ...(candidate.skills || [])].filter(Boolean).join(' ').toLowerCase().includes(needle)).slice(0, limit).map((candidate) => ({ ...candidate, role: candidate.role || candidate.title, contentSnippet: candidate.summary || candidate.notes })); return ok({ results, toolName: this.name, metadata: { query } }); } }
export class VectorSearchTool implements SearchTool<SearchToolParams, CandidateSearchRecord> { name = 'vector_search'; description = 'Rank local candidate profiles by query relevance.'; async execute(params: SearchToolParams): Promise<Result<SearchToolResult<CandidateSearchRecord>>> { const result = await semanticSearchService.search(params.query, { limit: params.limit || 10 }); return result.success ? ok({ results: result.data.map((candidate) => ({ id: candidate.id, name: candidate.name, similarity: candidate.similarity, skills: candidate.skills, role: String(candidate.metadata.role || '') })), toolName: this.name }) : err(result.error); } }
type CandidateReadRecord = { content: string | null; metadata: Record<string, unknown> };
export class CandidateReaderTool implements SearchTool<{ candidateId: string }, CandidateReadRecord> { name = 'candidate_reader'; description = 'Read a candidate profile from the local workspace.'; async execute({ candidateId }: { candidateId: string }): Promise<Result<SearchToolResult<CandidateReadRecord>>> { const candidate = readLocalCandidates().find((item) => item.id === candidateId); return ok({ results: candidate ? [{ content: candidate.summary || candidate.notes || null, metadata: candidate as unknown as Record<string, unknown> }] : [], toolName: this.name }); } }
type FactCheckRecord = { name: string; title: string; context: string };
export class FactCheckerTool implements SearchTool<{ company: string; role?: string }, FactCheckRecord> { name = 'fact_checker'; description = 'Compare a profile with local peers from the same company.'; async execute(params: { company: string; role?: string }): Promise<Result<SearchToolResult<FactCheckRecord>>> { const peers = readLocalCandidates().filter((candidate) => String(candidate.company || candidate.metadata?.company || '').toLowerCase().includes(params.company.toLowerCase())).slice(0, 5).map((candidate) => ({ name: candidate.name, title: candidate.role || candidate.title || 'Candidate', context: `${params.company} experience recorded in the local profile` })); return ok({ results: peers, toolName: this.name, metadata: { peerCount: peers.length } }); } }
type OutreachExample = { subject: string; tags: string[] };
export class OutreachPerformanceTool implements SearchTool<{ skills: string[]; role?: string }, OutreachExample> { name = 'outreach_performance'; description = 'Suggest locally available outreach patterns.'; async execute(params: { skills: string[]; role?: string }): Promise<Result<SearchToolResult<OutreachExample>>> { return ok({ results: [{ subject: `Quick question about your work`, tags: ['general'] }, { subject: `${params.role || 'Career'} opportunity`, tags: ['specialist'] }, { subject: `Your experience with ${params.skills[0] || 'this field'}`, tags: ['personalized'] }], toolName: this.name }); } }
export const agenticTools = { keyword: new KeywordSearchTool(), vector: new VectorSearchTool(), reader: new CandidateReaderTool(), factChecker: new FactCheckerTool(), outreach: new OutreachPerformanceTool() };
