import type { ScreeningResult } from './AutonomousScreeningAgent';
import type { TruthCheckPack } from './TruthCheckService';
import type { TruthCheckAnswerAssessment } from './TruthCheckAssessmentService';
export type DecisionType = 'screening' | 'interview' | 'shortlist_analysis';
export type DecisionValue = 'STRONG_PASS' | 'PASS' | 'BORDERLINE' | 'FAIL' | 'REJECTED' | 'HIRED';
export interface DecisionArtifactRecord { id: string; candidateId: string; candidateName?: string; jobId: string; jobTitle?: string; decisionType: DecisionType; decision: DecisionValue; score?: number; confidence?: number; summary?: string; details: Record<string, unknown>; rubricId?: string; rubricVersion?: number; externalId?: string; createdAt: string }
const KEY = 'talentSonar:decisionArtifacts';
const read = (): DecisionArtifactRecord[] => { try { const value = JSON.parse(localStorage.getItem(KEY) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } };
const writeArtifact = (artifact: DecisionArtifactRecord) => { const duplicate = (item: DecisionArtifactRecord) => item.candidateId === artifact.candidateId && item.jobId === artifact.jobId && item.decisionType === artifact.decisionType && item.externalId === artifact.externalId; localStorage.setItem(KEY, JSON.stringify([artifact, ...read().filter((item) => !duplicate(item))].slice(0, 3000))); };
const make = (value: Omit<DecisionArtifactRecord, 'id' | 'createdAt'>): DecisionArtifactRecord => ({ ...value, id: globalThis.crypto?.randomUUID?.() || `decision-${Date.now()}`, createdAt: new Date().toISOString() });
class DecisionArtifactService {
  async listArtifactsForCandidate({ candidateId, decisionType, limit = 200 }: { candidateId: string; decisionType?: DecisionType; limit?: number }): Promise<DecisionArtifactRecord[]> { return read().filter((item) => item.candidateId === candidateId && (!decisionType || item.decisionType === decisionType)).slice(0, limit); }
  async listArtifactsForJob({ jobId, decisionType, limit = 500 }: { jobId: string; decisionType?: DecisionType; limit?: number }): Promise<DecisionArtifactRecord[]> { return read().filter((item) => item.jobId === jobId && (!decisionType || item.decisionType === decisionType)).slice(0, limit); }
  async saveScreeningResult({ result, rubricVersion = 1, confidence, details = {} }: { result: ScreeningResult; rubricName?: string; rubricVersion?: number; confidence?: number; details?: Record<string, unknown> }): Promise<void> { writeArtifact(make({ candidateId: result.candidateId, candidateName: result.candidateName, jobId: result.jobId, jobTitle: result.jobTitle, decisionType: 'screening', decision: result.recommendation, score: result.score, confidence, summary: result.summary, details: { questions: result.questions || [], passed: result.passed, screenedAt: new Date(result.screenedAt).toISOString(), ...details }, rubricVersion, externalId: result.id })); }
  async saveTruthCheckAssessment(params: { candidateId: string; candidateName?: string; jobId: string; jobTitle?: string; truthCheck: TruthCheckPack; answers: TruthCheckAnswerAssessment[]; score: number; recommendation: ScreeningResult['recommendation']; summary: string; rubricName?: string; rubricVersion?: number; externalId?: string }): Promise<void> { writeArtifact(make({ candidateId: params.candidateId, candidateName: params.candidateName, jobId: params.jobId, jobTitle: params.jobTitle, decisionType: 'screening', decision: params.recommendation, score: params.score, summary: params.summary, details: { truthCheck: params.truthCheck, answers: params.answers, capturedBy: 'recruiter', capturedAt: new Date().toISOString() }, rubricVersion: params.rubricVersion || 1, externalId: params.externalId || 'truth_check_v1' })); }
  async listScreeningsForCandidate(candidateId: string, limit = 100): Promise<ScreeningResult[]> { return (await this.listArtifactsForCandidate({ candidateId, decisionType: 'screening', limit })).map((item) => ({ id: item.externalId || item.id, candidateId: item.candidateId, candidateName: item.candidateName || 'Candidate', jobId: item.jobId, jobTitle: item.jobTitle || 'Job', score: item.score || 0, passed: Boolean(item.details.passed ?? item.decision !== 'FAIL'), questions: Array.isArray(item.details.questions) ? item.details.questions as any : [], recommendation: item.decision as ScreeningResult['recommendation'], summary: item.summary || '', screenedAt: new Date(String(item.details.screenedAt || item.createdAt)) })); }
  async saveShortlistAnalysis(params: { candidateId: string; candidateName?: string; jobId: string; jobTitle?: string; score: number; decision: DecisionValue; summary?: string; details?: Record<string, unknown>; externalId?: string; rubricName?: string; rubricVersion?: number; confidence?: number }): Promise<void> { writeArtifact(make({ candidateId: params.candidateId, candidateName: params.candidateName, jobId: params.jobId, jobTitle: params.jobTitle, decisionType: 'shortlist_analysis', decision: params.decision, score: params.score, confidence: params.confidence, summary: params.summary, details: params.details || {}, rubricVersion: params.rubricVersion || 1, externalId: params.externalId || 'shortlist_v1' })); }
  async saveInterviewDebrief(params: { candidateId: string; candidateName?: string; jobId: string; jobTitle?: string; score: number; decision: DecisionValue; summary?: string; details?: Record<string, unknown>; externalId?: string; rubricName?: string; rubricVersion?: number; confidence?: number }): Promise<void> { writeArtifact(make({ candidateId: params.candidateId, candidateName: params.candidateName, jobId: params.jobId, jobTitle: params.jobTitle, decisionType: 'interview', decision: params.decision, score: params.score, confidence: params.confidence, summary: params.summary, details: params.details || {}, rubricVersion: params.rubricVersion || 1, externalId: params.externalId || 'interview_v1' })); }
  async listShortlistAnalysesForCandidate(candidateId: string, limit = 200): Promise<DecisionArtifactRecord[]> { return this.listArtifactsForCandidate({ candidateId, decisionType: 'shortlist_analysis', limit }); }
}
export const decisionArtifactService = new DecisionArtifactService();
