import type { Result } from '../types/result';
import { ok } from '../types/result';
import { readLocalCandidates } from './LocalCandidateStore';
export interface CompanyNode { id: number; name: string; industry: string; size: string; location: string; employee_count: number }
export interface SchoolNode { id: number; name: string; type: string; location: string; ranking: number }
export interface SkillNode { id: number; name: string; category: string; demand_score: number }
export interface CandidateRelationship { candidate_id: string; candidate_name: string; candidate_title: string; candidate_email: string; relationship_type: string; relationship_context: string }
export interface CareerPath { from_company: string; to_company: string; candidate_count: number; common_titles: string[] }
export interface SkillCluster { primary_skill: string; related_skills: string[]; candidate_count: number }
const values = (candidate: any, key: string): string[] => { const direct = candidate[key]; const meta = candidate.metadata?.[key]; const value = direct ?? meta; return Array.isArray(value) ? value.map(String) : value ? [String(value)] : []; };
const relationship = (candidate: any, type: string, context: string): CandidateRelationship => ({ candidate_id: candidate.id, candidate_name: candidate.name, candidate_title: candidate.currentRole || candidate.role || candidate.title || '', candidate_email: candidate.email || '', relationship_type: type, relationship_context: context });
class GraphQueryService {
  async findCandidatesByCompany(companyName: string): Promise<Result<CandidateRelationship[]>> { const needle = companyName.toLowerCase(); return ok(readLocalCandidates().filter((candidate) => [...values(candidate, 'companies'), ...values(candidate, 'company')].some((value) => value.toLowerCase().includes(needle))).map((candidate) => relationship(candidate, 'company', `Worked at ${companyName}`))); }
  async findCandidatesBySchool(schoolName: string): Promise<Result<CandidateRelationship[]>> { const needle = schoolName.toLowerCase(); return ok(readLocalCandidates().filter((candidate) => [...values(candidate, 'schools'), ...values(candidate, 'school')].some((value) => value.toLowerCase().includes(needle))).map((candidate) => relationship(candidate, 'school', `Studied at ${schoolName}`))); }
  async findCandidatesBySkill(skillName: string, _minProficiency?: string): Promise<Result<CandidateRelationship[]>> { const needle = skillName.toLowerCase(); return ok(readLocalCandidates().filter((candidate) => (candidate.skills || []).some((skill) => skill.toLowerCase().includes(needle))).map((candidate) => relationship(candidate, 'skill', `Lists ${skillName}`))); }
  async findCandidatesByMultipleCriteria(criteria: { companies?: string[]; schools?: string[]; skills?: string[] }): Promise<Result<CandidateRelationship[]>> { const candidates = readLocalCandidates().filter((candidate) => (!criteria.companies?.length || criteria.companies.some((term) => [...values(candidate, 'companies'), ...values(candidate, 'company')].some((value) => value.toLowerCase().includes(term.toLowerCase())))) && (!criteria.schools?.length || criteria.schools.some((term) => values(candidate, 'schools').some((value) => value.toLowerCase().includes(term.toLowerCase())))) && (!criteria.skills?.length || criteria.skills.some((term) => (candidate.skills || []).some((value) => value.toLowerCase().includes(term.toLowerCase()))))); return ok(candidates.map((candidate) => relationship(candidate, 'multi_criteria', `Matches ${[...(criteria.companies || []), ...(criteria.schools || []), ...(criteria.skills || [])].join(', ')}`))); }
  async findCareerPaths(_fromCompany?: string, _toCompany?: string): Promise<Result<CareerPath[]>> { return ok([]); }
  async findAlumniNetwork(schoolName: string, limit = 50): Promise<Result<CandidateRelationship[]>> { const result = await this.findCandidatesBySchool(schoolName); return result.success ? ok(result.data.slice(0, limit)) : result; }
  async findCompanyAlumniNetwork(companyName: string, limit = 50): Promise<Result<CandidateRelationship[]>> { const result = await this.findCandidatesByCompany(companyName); return result.success ? ok(result.data.slice(0, limit)) : result; }
  async findSkillClusters(primarySkill: string): Promise<Result<SkillCluster[]>> { const matching = readLocalCandidates().filter((candidate) => (candidate.skills || []).some((skill) => skill.toLowerCase() === primarySkill.toLowerCase())); const counts = new Map<string, number>(); matching.flatMap((candidate) => candidate.skills || []).filter((skill) => skill.toLowerCase() !== primarySkill.toLowerCase()).forEach((skill) => counts.set(skill, (counts.get(skill) || 0) + 1)); return ok(matching.length ? [{ primary_skill: primarySkill, related_skills: Array.from(counts.entries()).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([skill]) => skill), candidate_count: matching.length }] : []); }
  async find2ndDegreeConnections(candidateId: string): Promise<Result<CandidateRelationship[]>> { const candidate = readLocalCandidates().find((item) => item.id === candidateId); if (!candidate) return ok([]); const companies = [...values(candidate, 'companies'), ...values(candidate, 'company')]; return this.findCandidatesByMultipleCriteria({ companies }).then((result) => result.success ? ok(result.data.filter((item) => item.candidate_id !== candidateId)) : result); }
  async getAllCompanies(): Promise<Result<CompanyNode[]>> { const counts = new Map<string, number>(); readLocalCandidates().forEach((candidate) => [...values(candidate, 'companies'), ...values(candidate, 'company')].forEach((name) => counts.set(name, (counts.get(name) || 0) + 1))); return ok(Array.from(counts, ([name, employee_count], index) => ({ id: index + 1, name, industry: '', size: '', location: '', employee_count }))); }
  async getAllSchools(): Promise<Result<SchoolNode[]>> { const names = new Set(readLocalCandidates().flatMap((candidate) => values(candidate, 'schools'))); return ok(Array.from(names, (name, index) => ({ id: index + 1, name, type: '', location: '', ranking: 0 }))); }
  async getAllSkills(): Promise<Result<SkillNode[]>> { const counts = new Map<string, number>(); readLocalCandidates().flatMap((candidate) => candidate.skills || []).forEach((name) => counts.set(name, (counts.get(name) || 0) + 1)); return ok(Array.from(counts, ([name, demand_score], index) => ({ id: index + 1, name, category: '', demand_score }))); }
  async getGraphStats(): Promise<Result<{ totalCandidates: number; totalCompanies: number; totalSchools: number; totalSkills: number; totalRelationships: number }>> { const candidates = readLocalCandidates(); const companies = await this.getAllCompanies(); const schools = await this.getAllSchools(); const skills = await this.getAllSkills(); const totalCompanies = companies.success ? companies.data.length : 0; const totalSchools = schools.success ? schools.data.length : 0; const totalSkills = skills.success ? skills.data.length : 0; return ok({ totalCandidates: candidates.length, totalCompanies, totalSchools, totalSkills, totalRelationships: totalCompanies + totalSchools + totalSkills }); }
}
export const graphQueryService = new GraphQueryService();
