import type { InterviewSession } from './AutonomousInterviewAgent';
export interface InterviewSessionRecord { sessionId: string; interviewId?: string; candidateId: string; candidateName?: string; jobId: string; jobTitle?: string; meetingProvider: string; meetingLink?: string; startedAt: string; endedAt?: string; questions: unknown[]; missingQuestions: unknown[]; transcript: unknown[]; debrief: Record<string, unknown>; metadata: Record<string, unknown>; createdAt: string; updatedAt: string }
const KEY = 'talentSonar:interviewSessions';
const read = (): InterviewSessionRecord[] => { try { const value = JSON.parse(localStorage.getItem(KEY) || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } };
class InterviewSessionPersistenceService {
  async upsertSession(session: InterviewSession, metadata: Record<string, unknown> = {}): Promise<void> { const now = new Date().toISOString(); const existing = read().find((item) => item.sessionId === session.id); const record: InterviewSessionRecord = { sessionId: session.id, interviewId: session.interviewId, candidateId: session.candidateId, candidateName: session.candidateName, jobId: session.jobId, jobTitle: session.jobTitle, meetingProvider: session.meetingProvider, meetingLink: session.meetingLink, startedAt: new Date(session.startedAt).toISOString(), endedAt: session.endedAt ? new Date(session.endedAt).toISOString() : undefined, questions: session.questions || [], missingQuestions: session.missingQuestions || [], transcript: session.transcript || [], debrief: (session.debrief || {}) as Record<string, unknown>, metadata, createdAt: existing?.createdAt || now, updatedAt: now }; localStorage.setItem(KEY, JSON.stringify([record, ...read().filter((item) => item.sessionId !== record.sessionId)])); }
  async listForCandidate(candidateId: string, limit = 100): Promise<InterviewSessionRecord[]> { return read().filter((item) => item.candidateId === candidateId).slice(0, limit); }
}
export const interviewSessionPersistenceService = new InterviewSessionPersistenceService();
