import type { ClientPoolCriteria, EngagementFrequency } from './ConversationalEngagementService';

export type SharedTalentPool = { id: string; name: string; description: string; candidateIds: string[]; ownerUserId?: string; targetSkills?: string[]; targetSize?: number; clientCriteria?: ClientPoolCriteria; createdAt: string; updatedAt: string };
export type EngagementPreference = { candidateId: string; contactPermitted: boolean; preferredChannels: string[]; frequency?: EngagementFrequency; locale?: string; language?: string; timezone?: string; preferredStartTime?: string; preferredEndTime?: string; quietDays?: string[]; talentCommunityConsent?: boolean; optOutReason?: string; updatedAt: string };
export type EngagementMessage = { id: string; candidateId: string; jobId?: string; poolId?: string; createdByUserId?: string; provider: string; providerMessageId?: string; direction: 'outbound' | 'inbound'; subject: string; body: string; status: 'drafted' | 'sent' | 'delivered' | 'opened' | 'replied' | 'bounced' | 'failed'; sentAt?: string; openedAt?: string; repliedAt?: string; createdAt: string };
export type SharedTask = { id: string; sourceKey?: string; taskType: 'review' | 'feedback' | 'overdue' | 'engagement' | 'custom'; title: string; detail: string; candidateId?: string; jobId?: string; ownerUserId?: string; ownerRole?: string; dueAt?: string; status: 'open' | 'in_progress' | 'completed' | 'dismissed'; createdAt: string; updatedAt: string };
export type RequisitionSlaSettings = { jobId: string; ownerUserId?: string; ownerDisplay: string; hiringManagerUserId?: string; hiringManagerDisplay: string; targetStartDate: string; coverageTarget: number; shortlistTarget: number; stageSlaDays: number; feedbackSlaDays: number; updatedAt?: string };
export type CollaborationComment = { id: string; entityType: 'candidate' | 'job' | 'task' | 'talent_pool' | 'engagement_message'; entityId: string; body: string; authorId: string; createdAt: string; mentionedUserIds: string[] };
export type Collaborator = { userId: string; role: string; displayName: string };

type LocalWorkspace = { pools: SharedTalentPool[]; preferences: EngagementPreference[]; messages: EngagementMessage[]; tasks: SharedTask[]; sla: RequisitionSlaSettings[]; comments: CollaborationComment[] };
const emptyWorkspace = (): LocalWorkspace => ({ pools: [], preferences: [], messages: [], tasks: [], sla: [], comments: [] });
const key = (organizationId: string) => `talentSonar:${organizationId}:operations`;
const eventName = (organizationId: string) => `talentSonar:operations:${organizationId}`;
const id = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`;
function read(organizationId: string): LocalWorkspace { try { const parsed = JSON.parse(localStorage.getItem(key(organizationId)) ?? '{}') as Partial<LocalWorkspace>; return { pools: Array.isArray(parsed.pools) ? parsed.pools : [], preferences: Array.isArray(parsed.preferences) ? parsed.preferences : [], messages: Array.isArray(parsed.messages) ? parsed.messages : [], tasks: Array.isArray(parsed.tasks) ? parsed.tasks : [], sla: Array.isArray(parsed.sla) ? parsed.sla : [], comments: Array.isArray(parsed.comments) ? parsed.comments : [] }; } catch { return emptyWorkspace(); } }
function write(organizationId: string, value: LocalWorkspace) { localStorage.setItem(key(organizationId), JSON.stringify(value)); window.dispatchEvent(new CustomEvent(eventName(organizationId))); }

export const sharedOperationsService = {
  subscribe(organizationId: string, _collections: string[], onChange: () => void): () => void {
    const localHandler = () => onChange();
    const storageHandler = (event: StorageEvent) => { if (event.key === key(organizationId)) onChange(); };
    window.addEventListener(eventName(organizationId), localHandler);
    window.addEventListener('storage', storageHandler);
    return () => { window.removeEventListener(eventName(organizationId), localHandler); window.removeEventListener('storage', storageHandler); };
  },
  async listCollaborators(_organizationId: string): Promise<Collaborator[]> { return [{ userId: 'local-user', role: 'owner', displayName: 'Local user' }]; },
  async listPools(organizationId: string) { return read(organizationId).pools.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); },
  async createPool(organizationId: string, name: string, description: string, options: { ownerUserId?: string; targetSkills?: string[]; targetSize?: number } = {}) { const store = read(organizationId); const now = new Date().toISOString(); const pool: SharedTalentPool = { id: id(), name, description, candidateIds: [], ownerUserId: options.ownerUserId, targetSkills: options.targetSkills ?? [], targetSize: options.targetSize ?? 10, createdAt: now, updatedAt: now }; store.pools.unshift(pool); write(organizationId, store); return pool.id; },
  async updatePool(organizationId: string, poolId: string, updates: Pick<SharedTalentPool, 'name' | 'description' | 'ownerUserId' | 'targetSkills' | 'targetSize'> & { clientCriteria?: ClientPoolCriteria }) { const store = read(organizationId); store.pools = store.pools.map((pool) => pool.id === poolId ? { ...pool, ...updates, updatedAt: new Date().toISOString() } : pool); write(organizationId, store); },
  async addPoolMembers(organizationId: string, poolId: string, candidateIds: string[]) { const store = read(organizationId); store.pools = store.pools.map((pool) => pool.id === poolId ? { ...pool, candidateIds: Array.from(new Set([...pool.candidateIds, ...candidateIds])), updatedAt: new Date().toISOString() } : pool); write(organizationId, store); },
  async listPreferences(organizationId: string) { return read(organizationId).preferences; },
  async setPreference(organizationId: string, candidateId: string, contactPermitted: boolean, details: Partial<Omit<EngagementPreference, 'candidateId' | 'contactPermitted' | 'updatedAt'>> = {}) { const store = read(organizationId); const previous = store.preferences.find((item) => item.candidateId === candidateId); const value: EngagementPreference = { ...previous, ...details, candidateId, contactPermitted, preferredChannels: details.preferredChannels ?? previous?.preferredChannels ?? ['email'], updatedAt: new Date().toISOString() }; store.preferences = [...store.preferences.filter((item) => item.candidateId !== candidateId), value]; write(organizationId, store); },
  async listMessages(organizationId: string) { return read(organizationId).messages.sort((a, b) => b.createdAt.localeCompare(a.createdAt)); },
  async createMessage(organizationId: string, input: { candidateId: string; subject: string; body: string; status?: EngagementMessage['status']; provider?: string; providerMessageId?: string; createdByUserId?: string; jobId?: string; poolId?: string }) { const store = read(organizationId); const status = input.status ?? 'drafted'; store.messages.unshift({ id: id(), candidateId: input.candidateId, jobId: input.jobId, poolId: input.poolId, createdByUserId: input.createdByUserId ?? 'local-user', provider: input.provider ?? 'local', providerMessageId: input.providerMessageId, direction: 'outbound', subject: input.subject, body: input.body, status, sentAt: status === 'sent' ? new Date().toISOString() : undefined, createdAt: new Date().toISOString() }); write(organizationId, store); },
  async listTasks(organizationId: string) { return read(organizationId).tasks.sort((a, b) => (a.dueAt ?? '9999').localeCompare(b.dueAt ?? '9999')); },
  async upsertTasks(organizationId: string, tasks: Array<Omit<SharedTask, 'id' | 'createdAt' | 'updatedAt' | 'status'> & { status?: SharedTask['status'] }>) { const store = read(organizationId); const now = new Date().toISOString(); for (const task of tasks) { const index = task.sourceKey ? store.tasks.findIndex((item) => item.sourceKey === task.sourceKey) : -1; if (index >= 0) store.tasks[index] = { ...store.tasks[index], ...task, updatedAt: now }; else store.tasks.push({ ...task, id: id(), status: task.status ?? 'open', createdAt: now, updatedAt: now }); } write(organizationId, store); },
  async setTaskStatus(organizationId: string, taskId: string, status: SharedTask['status']) { const store = read(organizationId); store.tasks = store.tasks.map((task) => task.id === taskId ? { ...task, status, updatedAt: new Date().toISOString() } : task); write(organizationId, store); },
  async assignTask(organizationId: string, taskId: string, ownerUserId: string, ownerRole: string) { const store = read(organizationId); store.tasks = store.tasks.map((task) => task.id === taskId ? { ...task, ownerUserId, ownerRole, updatedAt: new Date().toISOString() } : task); write(organizationId, store); },
  async getSlaSettings(organizationId: string, jobId: string) { return read(organizationId).sla.find((item) => item.jobId === jobId) ?? null; },
  async listSlaSettings(organizationId: string) { return read(organizationId).sla; },
  async saveSlaSettings(organizationId: string, value: RequisitionSlaSettings) { const store = read(organizationId); store.sla = [...store.sla.filter((item) => item.jobId !== value.jobId), { ...value, updatedAt: new Date().toISOString() }]; write(organizationId, store); },
  async listComments(organizationId: string, entityType: CollaborationComment['entityType'], entityId: string) { return read(organizationId).comments.filter((item) => item.entityType === entityType && item.entityId === entityId).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); },
  async addComment(organizationId: string, entityType: CollaborationComment['entityType'], entityId: string, body: string, mentionedUserIds: string[] = []) { const store = read(organizationId); store.comments.push({ id: id(), entityType, entityId, body, authorId: 'local-user', createdAt: new Date().toISOString(), mentionedUserIds }); write(organizationId, store); },
};
