import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AtSign, MessageSquare, Send } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { sharedOperationsService, type CollaborationComment, type Collaborator } from '../services/SharedOperationsService';

const CollaborationThread: React.FC<{ entityType: CollaborationComment['entityType']; entityId: string; title?: string }> = ({ entityType, entityId, title = 'Team discussion' }) => {
  const { activeOrganization, isDemoMode } = useAuth();
  const [comments, setComments] = useState<CollaborationComment[]>([]); const [collaborators, setCollaborators] = useState<Collaborator[]>([]); const [body, setBody] = useState(''); const [mention, setMention] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { if (!activeOrganization || isDemoMode) return; try { const [nextComments, nextCollaborators] = await Promise.all([sharedOperationsService.listComments(activeOrganization.organizationId, entityType, entityId), sharedOperationsService.listCollaborators(activeOrganization.organizationId)]); setComments(nextComments); setCollaborators(nextCollaborators); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load team discussion.'); } }, [activeOrganization, entityId, entityType, isDemoMode]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!activeOrganization || isDemoMode) return; return sharedOperationsService.subscribe(activeOrganization.organizationId, ['collaboration_comments', 'collaboration_mentions'], () => void load()); }, [activeOrganization, isDemoMode, load]);
  const names = useMemo(() => new Map(collaborators.map((person) => [person.userId, person.displayName])), [collaborators]);
  const submit = async () => { if (!activeOrganization || !body.trim() || isDemoMode) return; setSaving(true); try { await sharedOperationsService.addComment(activeOrganization.organizationId, entityType, entityId, body.trim(), mention ? [mention] : []); setBody(''); setMention(''); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not add comment.'); } finally { setSaving(false); } };
  if (isDemoMode) return <div className="rounded-xl border border-dashed border-slate-700 p-3 text-xs text-slate-500">Team comments and mentions are available in a connected organization workspace.</div>;
  return <section className="rounded-xl border border-slate-700 bg-slate-900/40 p-4"><div className="flex items-center gap-2"><MessageSquare className="h-4 w-4 text-sky-300" /><h3 className="text-sm font-bold text-white">{title}</h3><span className="text-xs text-slate-500">{comments.length}</span></div>{error && <p className="mt-2 text-xs text-amber-300">{error}</p>}<div className="mt-3 max-h-44 space-y-2 overflow-y-auto">{comments.map((comment) => <div key={comment.id} className="rounded-lg bg-slate-950/50 p-2.5"><p className="text-xs font-semibold text-sky-200">{names.get(comment.authorId) ?? 'Workspace member'} <span className="ml-1 font-normal text-slate-600">{new Date(comment.createdAt).toLocaleString()}</span></p><p className="mt-1 text-sm text-slate-300">{comment.body}</p>{comment.mentionedUserIds.length > 0 && <p className="mt-1 flex items-center gap-1 text-xs text-violet-300"><AtSign className="h-3 w-3" />{comment.mentionedUserIds.map((id) => names.get(id) ?? id).join(', ')}</p>}</div>)}{!comments.length && <p className="py-3 text-center text-xs text-slate-500">No comments yet.</p>}</div><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><textarea value={body} onChange={(event) => setBody(event.target.value)} rows={2} placeholder="Add context or a decision note…" className="rounded-lg border border-slate-700 bg-slate-950 p-2 text-sm text-white outline-none focus:border-sky-400" /><div className="flex flex-col gap-2"><select value={mention} onChange={(event) => setMention(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs text-slate-300"><option value="">No mention</option>{collaborators.map((person) => <option key={person.userId} value={person.userId}>@{person.displayName}</option>)}</select><button type="button" onClick={() => void submit()} disabled={saving || !body.trim()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-sky-500 px-3 py-2 text-xs font-bold text-white disabled:opacity-50"><Send className="h-3.5 w-3.5" />Comment</button></div></div></section>;
};
export default CollaborationThread;
