import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BriefcaseBusiness, Building2, Clock3, MapPin, Search, Sparkles } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { careerSiteService, type PublishedCareerJob } from '../services/CareerSiteService';

const CareerSitePage: React.FC = () => {
  const { organization = 'local-workspace' } = useParams(); const [jobs, setJobs] = useState<PublishedCareerJob[]>([]); const [name, setName] = useState('Careers'); const [query, setQuery] = useState(''); const [department, setDepartment] = useState('all'); const [location, setLocation] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void careerSiteService.publicJobs(organization).then((result) => { setJobs(result.jobs); setName(result.organization.name); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Opportunities could not be loaded.')).finally(() => setLoading(false)); }, [organization]);
  const departments = [...new Set(jobs.map((job) => job.department).filter(Boolean))].sort(); const locations = [...new Set(jobs.map((job) => job.location).filter(Boolean))].sort();
  const filtered = useMemo(() => jobs.filter((job) => { const text = `${job.title} ${job.department} ${job.location} ${job.requiredSkills.join(' ')}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (department === 'all' || job.department === department) && (location === 'all' || job.location === location); }), [jobs, query, department, location]);
  return <CareerShell organization={organization} name={name}><section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-sky-950 via-slate-900 to-indigo-950 px-6 py-14 text-white sm:px-12 lg:py-20"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-sky-300">Build what comes next</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">Find work where your skills matter.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Explore open opportunities, understand what success looks like, and apply through a clear, candidate-controlled process.</p></div><div className="mt-9 grid gap-3 rounded-2xl border border-white/10 bg-white/5 p-3 backdrop-blur md:grid-cols-[1fr_220px_220px]"><label className="relative"><span className="sr-only">Search opportunities</span><Search className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search roles or skills" className="w-full rounded-xl border border-white/10 bg-slate-950/70 py-3.5 pl-12 pr-4 text-white outline-none focus:border-sky-400" /></label><Filter value={department} onChange={setDepartment} label="All departments" options={departments} /><Filter value={location} onChange={setLocation} label="All locations" options={locations} /></div></section><section className="py-10"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-sky-700">Open opportunities</p><h2 className="mt-1 text-3xl font-black text-slate-950">{filtered.length} role{filtered.length === 1 ? '' : 's'} available</h2></div><p className="text-sm text-slate-500">Only active, approved opportunities are shown.</p></div>{error && <p className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{loading ? <div className="mt-7 grid gap-4 md:grid-cols-2"><Skeleton /><Skeleton /></div> : <div className="mt-7 grid gap-4 md:grid-cols-2">{filtered.map((job) => <JobCard key={job.id} job={job} organization={organization} />)}{!filtered.length && <div className="col-span-full rounded-2xl border border-dashed border-slate-300 p-14 text-center"><BriefcaseBusiness className="mx-auto h-9 w-9 text-slate-400" /><p className="mt-3 font-bold text-slate-900">No opportunities match these filters</p><p className="mt-1 text-sm text-slate-500">Try a broader keyword, department, or location.</p></div>}</div>}</section><section className="mb-10 rounded-3xl bg-sky-50 p-7 sm:p-10"><Sparkles className="h-7 w-7 text-sky-700" /><h2 className="mt-4 text-2xl font-black text-slate-950">Not ready to apply?</h2><p className="mt-2 max-w-2xl text-slate-600">Return as new opportunities are published. Talent-community registration will only contact you when current consent and preferences are recorded.</p></section></CareerShell>;
};
export const CareerShell: React.FC<{ organization: string; name: string; children: React.ReactNode }> = ({ organization, name, children }) => <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link to={`/careers/${organization}`} className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-sky-600 text-white"><Building2 className="h-5 w-5" /></span><span><span className="block font-black">{name}</span><span className="block text-xs text-slate-500">Careers</span></span></Link><Link to={`/careers/${organization}`} className="text-sm font-bold text-sky-700">View all jobs</Link></div></header><main className="mx-auto max-w-7xl px-5">{children}</main><footer className="mt-8 border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-7 text-xs text-slate-500 sm:flex-row sm:justify-between"><span>Equal opportunity and role-relevant assessment.</span><span>Candidate information is used only for authorized recruiting purposes.</span></div></footer></div>;
const Filter: React.FC<{ value: string; onChange: (value: string) => void; label: string; options: string[] }> = ({ value, onChange, label, options }) => <select value={value} onChange={(event) => onChange(event.target.value)} className="rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3.5 text-white outline-none focus:border-sky-400"><option value="all">{label}</option>{options.map((option) => <option key={option}>{option}</option>)}</select>;
const JobCard: React.FC<{ job: PublishedCareerJob; organization: string }> = ({ job, organization }) => <Link to={`/careers/${organization}/jobs/${job.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-300 hover:shadow-lg"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-sky-700">{job.department}</p><h3 className="mt-1 text-xl font-black text-slate-950 group-hover:text-sky-700">{job.title}</h3></div><ArrowRight className="h-5 w-5 text-slate-400 group-hover:text-sky-600" /></div><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-500"><span className="flex items-center gap-1.5"><MapPin className="h-4 w-4" />{job.location}</span>{job.type && <span className="flex items-center gap-1.5"><BriefcaseBusiness className="h-4 w-4" />{job.type}</span>}<span className="flex items-center gap-1.5"><Clock3 className="h-4 w-4" />Posted {new Date(job.publishedAt).toLocaleDateString()}</span></div><div className="mt-5 flex flex-wrap gap-2">{job.requiredSkills.slice(0, 4).map((skill) => <span key={skill} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{skill}</span>)}</div></Link>;
const Skeleton = () => <div className="h-44 animate-pulse rounded-2xl bg-slate-200" />;
export default CareerSitePage;
