import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { CalendarClock, CheckCircle2, Languages, ShieldCheck } from 'lucide-react';
import { candidateConversationPlatformService } from '../services/CandidateConversationPlatformService';
import type { LanguageAssessment, PhoneSession } from '../api/_lib/conversationStore';

const ExternalConversationPage: React.FC = () => {
  const { organizationId = '', token = '' } = useParams(); const [assessment, setAssessment] = useState<LanguageAssessment>(); const [phone, setPhone] = useState<PhoneSession>(); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  const [scores, setScores] = useState({ reading: 70, writing: 70, listening: 70, speaking: 70, overall: 70, cefr: 'B2' }); const [evidence, setEvidence] = useState(''); const [slot, setSlot] = useState(''); const [consent, setConsent] = useState(false);
  useEffect(() => { void candidateConversationPlatformService.external(organizationId, token).then((result) => { setAssessment(result.assessment); setPhone(result.phoneSession); setSlot(result.phoneSession?.availableSlots[0] ?? ''); if (!result.assessment && !result.phoneSession) setError('This invitation is invalid or no longer available.'); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Invitation could not be loaded.')); }, [organizationId, token]);
  const submitAssessment = async () => { try { await candidateConversationPlatformService.submitAssessment(organizationId, { token, scores, evidence: evidence.split('\n').map((item) => item.trim()).filter(Boolean) }); setDone(true); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Assessment could not be submitted.'); } };
  const schedule = async () => { if (!consent) return setError('Recording consent is required before scheduling this phone screen.'); try { await candidateConversationPlatformService.schedulePhone(organizationId, token, slot); setDone(true); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Phone screen could not be scheduled.'); } };
  if (done) return <State title="Thank you" detail="Your response has been recorded. A recruiter will review the evidence and contact you about the next step." />;
  return <main className="min-h-screen bg-slate-950 px-4 py-10 text-white"><div className="mx-auto max-w-3xl space-y-5"><header className="rounded-2xl border border-slate-700 bg-slate-800 p-6"><p className="text-sm font-bold text-violet-300">Talent Sonar candidate experience</p><h1 className="mt-1 text-3xl font-bold">Assessment & conversation</h1><p className="mt-2 text-sm text-slate-400">Your results support recruiter review and never create an automatic rejection.</p></header>{error && <p className="rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}
    {assessment && <section className="rounded-2xl border border-slate-700 bg-slate-800 p-6"><div className="flex gap-3"><Languages className="text-violet-300" /><div><h2 className="text-xl font-bold">{assessment.languageLabel} assessment</h2><p className="text-sm text-slate-400">Target level: {assessment.requestedLevel}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{(['reading','writing','listening','speaking'] as const).map((key) => <label key={key} className="text-xs font-bold capitalize text-slate-400">{key} score<input type="number" min="0" max="100" value={scores[key]} onChange={(event) => setScores({ ...scores, [key]: Number(event.target.value) })} className="mt-1.5 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-white" /></label>)}<label className="text-xs font-bold text-slate-400">CEFR result<select value={scores.cefr} onChange={(event) => setScores({ ...scores, cefr: event.target.value })} className="mt-1.5 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-white">{['A1','A2','B1','B2','C1','C2'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-bold text-slate-400">Overall score<input type="number" min="0" max="100" value={scores.overall} onChange={(event) => setScores({ ...scores, overall: Number(event.target.value) })} className="mt-1.5 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-white" /></label></div><label className="mt-4 block text-xs font-bold text-slate-400">Evidence or provider references<textarea rows={5} value={evidence} onChange={(event) => setEvidence(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-white" /></label><button type="button" onClick={() => void submitAssessment()} className="mt-4 rounded-lg bg-violet-500 px-5 py-3 font-bold">Submit for human review</button></section>}
    {phone && <section className="rounded-2xl border border-slate-700 bg-slate-800 p-6"><div className="flex gap-3"><CalendarClock className="text-sky-300" /><div><h2 className="text-xl font-bold">Schedule your phone conversation</h2><p className="text-sm text-slate-400">{phone.jobTitle || 'Talent community conversation'} · {phone.durationMinutes} minutes</p></div></div><div className="mt-5 rounded-xl border border-slate-700 bg-slate-950/30 p-4"><p className="text-xs font-bold uppercase text-sky-300">Conversation topics</p><ul className="mt-2 space-y-2 text-sm text-slate-300">{phone.questions.map((question) => <li key={question}>• {question}</li>)}</ul></div><div className="mt-5 space-y-2">{phone.availableSlots.map((item) => <label key={item} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-4 ${slot === item ? 'border-sky-400 bg-sky-400/10' : 'border-slate-700'}`}><input type="radio" checked={slot === item} onChange={() => setSlot(item)} /><span>{new Date(item).toLocaleString()}</span></label>)}</div><label className="mt-5 flex items-start gap-3 rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-4"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-1" /><span className="text-sm leading-6 text-slate-300"><strong className="text-white">Recording and transcription consent.</strong> I agree that this phone conversation may be recorded and transcribed for recruiter review. Automated findings do not make the hiring decision.</span></label><button type="button" onClick={() => void schedule()} className="mt-4 rounded-lg bg-sky-500 px-5 py-3 font-bold">Confirm phone screen</button></section>}
    <div className="flex gap-2 rounded-xl border border-slate-800 p-4 text-xs leading-5 text-slate-500"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-300" />Your preferences, consent, assessment and call evidence are recorded for authorized recruiting users. Contact your recruiter to withdraw or correct information.</div></div></main>;
};
const State: React.FC<{ title: string; detail: string }> = ({ title, detail }) => <main className="grid min-h-screen place-items-center bg-slate-950 p-6 text-white"><div className="max-w-lg rounded-2xl border border-emerald-400/20 bg-slate-800 p-8 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-300" /><h1 className="mt-4 text-2xl font-bold">{title}</h1><p className="mt-2 text-slate-400">{detail}</p></div></main>;
export default ExternalConversationPage;
