import type { IncomingMessage, ServerResponse } from 'node:http';
import { z } from 'zod';
import { careerId, careerNow, careerSlug, readCareerStore, updateCareerStore, type PublishedCareerJob } from './_lib/careerStore';

const send = (res: ServerResponse, status: number, body: unknown) => { res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.setHeader('Cache-Control', 'no-store'); res.end(JSON.stringify(body)); };
async function json(req: IncomingMessage) { const chunks: Buffer[] = []; let size = 0; for await (const chunk of req) { const part = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk); size += part.length; if (size > 1024 * 1024) throw new Error('Request too large.'); chunks.push(part); } return JSON.parse(Buffer.concat(chunks).toString('utf8') || '{}') as Record<string, unknown>; }
const base = z.object({ action: z.string(), organizationId: z.string().min(1).max(200) });
const publicJob = (job: PublishedCareerJob) => ({ ...job, assignedRecruiter: undefined });
const isLive = (job: PublishedCareerJob) => job.status === 'published' && (!job.expiresAt || Date.parse(job.expiresAt) > Date.now());

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  try {
    const url = new URL(req.url || '/', 'http://localhost');
    if (req.method === 'GET') {
      const organizationId = url.searchParams.get('organizationId') || url.searchParams.get('organization') || ''; if (!organizationId) return send(res, 400, { ok: false, message: 'Organization is required.' });
      const store = await readCareerStore(organizationId); const admin = url.searchParams.get('scope') === 'admin';
      if (admin) return send(res, 200, { ok: true, store });
      const slug = url.searchParams.get('job'); if (slug) { const job = store.jobs.find((item) => item.slug === slug); if (!job) return send(res, 404, { ok: false, errorCode: 'NOT_FOUND', message: 'This opportunity could not be found.' }); if (!isLive(job)) return send(res, 410, { ok: false, errorCode: 'NOT_AVAILABLE', message: 'This opportunity is no longer accepting applications.' }); return send(res, 200, { ok: true, job: publicJob(job) }); }
      return send(res, 200, { ok: true, organization: { id: organizationId, name: organizationId === 'local-workspace' ? 'Talent Sonar' : organizationId.replace(/-/g, ' ') }, jobs: store.jobs.filter(isLive).map(publicJob) });
    }
    if (req.method !== 'POST') return send(res, 405, { ok: false, message: 'GET or POST only.' });
    const raw = await json(req); const parsed = base.safeParse(raw); if (!parsed.success) return send(res, 400, { ok: false, message: parsed.error.issues[0]?.message || 'Invalid request.' }); const { action, organizationId } = parsed.data; const timestamp = careerNow();
    const result = await updateCareerStore(organizationId, (store) => {
      if (action === 'publish') {
        const input = z.object({ organizationSlug: z.string().min(1), job: z.object({ id: z.string(), title: z.string().min(1), department: z.string(), location: z.string(), type: z.string().optional(), salaryRange: z.string().optional(), requiredSkills: z.array(z.string()), niceToHaveSkills: z.array(z.string()).optional(), description: z.string().min(1), company: z.string().optional(), headcount: z.number().optional() }), expiresAt: z.string().optional(), assignedRecruiter: z.object({ userId: z.string(), displayName: z.string(), email: z.string().optional() }).optional() }).parse(raw);
        const previous = store.jobs.find((item) => item.jobId === input.job.id); const slugBase = careerSlug(input.job.title); const slug = previous?.slug ?? (store.jobs.some((item) => item.slug === slugBase && item.jobId !== input.job.id) ? `${slugBase}-${input.job.id.slice(0, 6)}` : slugBase); const job: PublishedCareerJob = { id: previous?.id ?? careerId(), organizationId, organizationSlug: input.organizationSlug, jobId: input.job.id, slug, title: input.job.title, department: input.job.department, location: input.job.location, type: input.job.type, salaryRange: input.job.salaryRange, requiredSkills: input.job.requiredSkills, niceToHaveSkills: input.job.niceToHaveSkills ?? [], description: input.job.description, company: input.job.company, headcount: input.job.headcount, status: 'published', publishedAt: previous?.publishedAt ?? timestamp, expiresAt: input.expiresAt, assignedRecruiter: input.assignedRecruiter, updatedAt: timestamp }; store.jobs = [job, ...store.jobs.filter((item) => item.jobId !== job.jobId)]; return job;
      }
      if (action === 'unpublish') { const input = z.object({ jobId: z.string(), status: z.enum(['paused', 'closed']).default('paused') }).parse(raw); const job = store.jobs.find((item) => item.jobId === input.jobId); if (!job) throw new Error('Published job not found.'); job.status = input.status; job.updatedAt = timestamp; return job; }
      if (action === 'apply') {
        const input = z.object({ jobSlug: z.string(), candidate: z.object({ name: z.string().min(2), email: z.string().email(), phone: z.string().optional(), role: z.string().optional(), location: z.string().optional(), experienceYears: z.number().optional(), skills: z.array(z.string()).default([]), summary: z.string().default(''), education: z.array(z.string()).default([]), languages: z.array(z.object({ language: z.string(), level: z.string() })).default([]), fileName: z.string().optional() }), answers: z.object({ eligibility: z.string().optional(), availability: z.string().optional(), profileUrl: z.string().optional() }), consentConfirmed: z.literal(true), privacyAccepted: z.literal(true) }).parse(raw); const job = store.jobs.find((item) => item.slug === input.jobSlug); if (!job || !isLive(job)) throw new Error('This opportunity is no longer accepting applications.'); const duplicate = store.applications.find((item) => item.jobId === job.jobId && item.candidate.email.toLowerCase() === input.candidate.email.toLowerCase() && item.status !== 'withdrawn'); const candidateId = duplicate?.candidateId ?? careerId(); const application = { id: careerId(), candidateId, organizationId, publishedJobId: job.id, jobId: job.jobId, jobTitle: job.title, recruiterUserId: job.assignedRecruiter?.userId, candidate: input.candidate, answers: input.answers, consentCapturedAt: timestamp, privacyAcceptedAt: timestamp, status: duplicate ? 'duplicate_review' as const : 'submitted' as const, duplicateApplicationId: duplicate?.id, submittedAt: timestamp }; store.applications.unshift(application); store.notifications.unshift({ id: careerId(), applicationId: application.id, organizationId, recruiterUserId: application.recruiterUserId, jobId: job.jobId, candidateId, title: `New application: ${input.candidate.name}`, detail: `${job.title}${duplicate ? ' · possible duplicate' : ''}`, createdAt: timestamp }); return { applicationId: application.id, candidateId, status: application.status, confirmationToken: application.id };
      }
      if (action === 'mark_synced') { const input = z.object({ applicationId: z.string() }).parse(raw); const application = store.applications.find((item) => item.id === input.applicationId); if (!application) throw new Error('Application not found.'); application.status = 'synced'; application.syncedAt = timestamp; const notification = store.notifications.find((item) => item.applicationId === application.id); if (notification) notification.acknowledgedAt = timestamp; return application; }
      throw new Error(`Unsupported action: ${action}`);
    });
    return send(res, 200, { ok: true, result });
  } catch (error) { const message = error instanceof Error ? error.message : 'Careers request failed.'; return send(res, message === 'Request too large.' ? 413 : /no longer accepting/.test(message) ? 410 : 400, { ok: false, message }); }
}
